# Generated by Django 4.2.4 on 2023-09-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='stripe_id платежа'),
        ),
    ]
